### ISSUE TITLE
[ENHANCEMENT] WYSIWYG

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#11]
Please do these following requests: 
- Remove "Tell a story" on WYSIWYG
- Enlarge WYSIWYG during run time / preview
- Enable scroll bar  when the text is too long ?
- Able to submit the wysiwyg function 's value

**Comment by bubuzzz** [comment]
fixed in https://github.com/apollo-forms/mantra-react-form-builder/commit/25bb51b2f90cbf650cae6a56eabac06297112bd9
