### ISSUE TITLE
[BUG] Reorder fields

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#12]
I have 3 fields

when I edit the name for the field (aaaa), it will go to bottom(reorder the field)
![image](https://cloud.githubusercontent.com/assets/14065403/17163216/3d69e910-5400-11e6-8a11-9e56dd9bcd11.png)

**Comment by bubuzzz** [comment]
Fixed in https://github.com/apollo-forms/mantra-react-form-builder/commit/65ffc5b48b1ab85c0f425e634a8947889279b9ae
