### ISSUE TITLE
[BUG] Information is not loaded back when editing the field

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#2]
As displayed below, I am entering information for this field
![image](https://cloud.githubusercontent.com/assets/14065403/17161230/27b22530-53ef-11e6-8ea4-58ca2419d9ae.png)

Then I click submit and it will display
![image](https://cloud.githubusercontent.com/assets/14065403/17161241/41336032-53ef-11e6-9007-50d6034c7228.png)

Then I try to edit any field, and it can't load all information
![image](https://cloud.githubusercontent.com/assets/14065403/17161287/8c4d8c14-53ef-11e6-8cec-1e189086aa41.png)

**Comment by bubuzzz** [comment]
Fix at https://github.com/apollo-forms/mantra-react-form-builder/commit/e5adab1139c010f309e6f1cdafaf9293cdeb795d
