### ISSUE TITLE
radio button / checkbox as main focus

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#38]
Currently our focus is in the component, however this can't be done if the component is label / array / object. We need to have a checkbox / radiobutton to indicate as a main focus. Each form should only have 1 active main focus.

**Comment by danutc** [comment]
To me we need a checkbox to the right of the form element (next to the other buttons).

When the user toggles the checkbox with the mouse we clear all the other checkboxes (from the other form fields on the page).

The outcome is that:

- only one line is selected or
- no line.
