### ISSUE TITLE
[NEW] Positioning

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#4]
Please make a feature to change the position of the fields such as arrow button up and down to adjust the position for each field

**Comment by bubuzzz** [comment]
Fixed in https://github.com/apollo-forms/mantra-react-form-builder/commit/05a3f9b52243340433cd45d1dc55bceb210632ef

**Comment by hnandarusdy** [comment]
There is a bug when we re-order the position, It won't re-order in preview unless we add another component.

**Comment by hnandarusdy** [comment]
Also in WYSIWYG keep duplicated when it is reordered

**Comment by bubuzzz** [comment]
Fixed in https://github.com/apollo-forms/mantra-react-form-builder/commit/3e6f9451016816e0084b9201228abd1a3b6a8003
