### ISSUE TITLE
[BUG] Sync display between designer and preview 

### ISSUE THREAD

**Issue by hnandarusdy** [apollo-forms/mantra-react-form-builder#5]
I have a screen shot of form builder view: 
![image](https://cloud.githubusercontent.com/assets/14065403/17161612/3e3b7d44-53f2-11e6-8258-bfb007486098.png)

To make it like that, simply change the class to **col-md-3** for each field. It will shorten the field afterwards.

Then in "preview" mode, it displays like this
![image](https://cloud.githubusercontent.com/assets/14065403/17161647/8f609650-53f2-11e6-9b0d-35cab715dd89.png)

So, please display the form builder to be similar with preview mode

**Comment by danutc** [comment]
The reason design view is different from preview is because in design view we have the settings and delete links on the right of the field.

One option is to make the settings and delete links shown on the right of each field as floating on the field.

**Comment by hnandarusdy** [comment]
It is too overkill and not that worth to build it and therefore close this ticket
